# تكوين GitHub Stale Bot
# https://github.com/actions/stale

# عدد الأيام قبل وضع علامة على المشكلة كغير نشطة
daysUntilStale: 60
# عدد الأيام قبل إغلاق المشكلة غير النشطة
daysUntilClose: 7
# المشكلات ذات هذه التسميات لن تتم معاملتها كغير نشطة
exemptLabels:
  - pinned
  - security
  - bug
  - enhancement
# التسمية التي ستتم إضافتها عندما تصبح المشكلة غير نشطة
staleLabel: wontfix
# التعليق الذي سيتم نشره عندما تتم وضع علامة على المشكلة كغير نشطة
markComment: >
  هذه المشكلة تم وضع علامة عليها تلقائيًا كغير نشطة بسبب عدم وجود نشاط حديث.
  سيتم إغلاقها إذا لم يكن هناك نشاط إضافي. شكرًا لمساهمتك.
# التعليق الذي سيتم نشره عندما يتم إغلاق المشكلة
closeComment: >
  هذه المشكلة تم إغلاقها تلقائيًا بسبب عدم وجود نشاط. يرجى إعادة فتحها إذا كانت لا تزال ذات صلة.
# تحديد ما إذا كان سيتم معالجة المشكلات فقط (لا طلبات السحب)
onlyIssues: false
# تحديد ما إذا كان سيتم معالجة طلبات السحب فقط (لا المشكلات)
onlyPRs: false
# تحديد ما إذا كان سيتم تجاهل المشكلات المعينة
exemptAssignees: false
# تحديد ما إذا كان سيتم تجاهل المشكلات ذات المشاريع
exemptProjects: false
# تحديد ما إذا كان سيتم تجاهل المشكلات ذات المعالم
exemptMilestones: false
# تحديد ما إذا كان سيتم فحص المشكلات المغلقة
processIssuesOnly: true